"""
Django settings for handmade_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
load_dotenv(BASE_DIR / '.env')

import sys
print("=== STARTING DJANGO APPLICATION ===", file=sys.stderr)
print(f"DEBUG={os.getenv('DEBUG')}", file=sys.stderr)
print(f"PORT={os.getenv('PORT')}", file=sys.stderr)
print(f"DATABASE_URL is set: {bool(os.getenv('DATABASE_URL'))}", file=sys.stderr)
print(f"PGHOST is set: {bool(os.getenv('PGHOST'))}", file=sys.stderr)
print(f"PGPASSWORD is set: {bool(os.getenv('PGPASSWORD'))}", file=sys.stderr)
print("===================================", file=sys.stderr)


# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_DEFAULT = 'django-insecure-m8lxy+&rpjzpr(c)x4@(7r+!x(!j_t=@=gc7xykuig954sz$df'
SECRET_KEY = os.getenv('SECRET_KEY', _SECRET_KEY_DEFAULT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ['true', '1']

# In production, crash loudly if insecure defaults are still in use
if not DEBUG:
    if SECRET_KEY == _SECRET_KEY_DEFAULT or 'insecure' in SECRET_KEY:
        raise ValueError(
            "SECURITY ERROR: SECRET_KEY must be set to a secure value in production. "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

# Parse allowed hosts
allowed_hosts_raw = os.getenv('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_raw.split(',') if h.strip()]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Local Modular Apps
    'accounts',
    'products',
    'reviews',
    'cart',
    'orders',
    'payments',
    'dashboard',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Put right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'handmade_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'handmade_backend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'handmade_backend.wsgi.application'

# Database
# Connect to Railway Postgres using DATABASE_URL or individual PG/POSTGRES environment variables
db_config = dj_database_url.config(
    default=f"sqlite:///{BASE_DIR}/db.sqlite3",
    conn_max_age=600
)

# Overwrite / update with individual Railway PostgreSQL variables if present.
# This prevents authentication failures if DATABASE_URL has an outdated password.
pg_host = os.getenv('PGHOST') or os.getenv('POSTGRES_HOST')
if pg_host:
    db_config.update({
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': pg_host,
        'PORT': os.getenv('PGPORT') or os.getenv('POSTGRES_PORT') or db_config.get('PORT', '5432'),
        'USER': os.getenv('PGUSER') or os.getenv('POSTGRES_USER') or db_config.get('USER', 'postgres'),
        'PASSWORD': os.getenv('PGPASSWORD') or os.getenv('POSTGRES_PASSWORD') or db_config.get('PASSWORD'),
        'NAME': os.getenv('PGDATABASE') or os.getenv('POSTGRES_DB') or db_config.get('NAME', 'railway'),
    })

DATABASES = {
    'default': db_config
}


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# =============================================================================
# JWT Key Resolution — Three-tier fallback chain
# Priority:  ACCESS_TOKEN_SECRET  →  JWT_SECRET_KEY  →  SECRET_KEY (dev only)
#
# ACCESS_TOKEN_SECRET:  Signs short-lived access tokens  (1 day)
# REFRESH_TOKEN_SECRET: Signs long-lived refresh tokens  (7 days)
#   └─ SimpleJWT uses a single SIGNING_KEY for both token types (HS256).
#      REFRESH_TOKEN_SECRET is stored and validated at the app layer when
#      ROTATE_REFRESH_TOKENS=True so that rotate-on-use is enforced.
# =============================================================================
_JWT_SECRET_KEY      = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
_ACCESS_TOKEN_SECRET = os.getenv('ACCESS_TOKEN_SECRET', _JWT_SECRET_KEY)
_REFRESH_TOKEN_SECRET = os.getenv('REFRESH_TOKEN_SECRET', _JWT_SECRET_KEY)

SIMPLE_JWT = {
    # Lifetimes
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Signing — access tokens use ACCESS_TOKEN_SECRET
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': _ACCESS_TOKEN_SECRET,
    'VERIFYING_KEY': None,  # Not required for symmetric HS256

    # Refresh token rotation (set True in production to invalidate old refresh tokens)
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    # Token payload
    'UPDATE_LAST_LOGIN': False,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Header format: "Authorization: Bearer <token>"
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Expose refresh secret so it can be referenced from views if needed
JWT_REFRESH_SIGNING_KEY = _REFRESH_TOKEN_SECRET

# CORS Configuration
cors_origins_raw = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_origins_raw:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins_raw.split(',') if o.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins for admin panel secure forms in production
csrf_trusted_raw = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_raw:
    CSRF_TRUSTED_ORIGINS = [t.strip() for t in csrf_trusted_raw.split(',') if t.strip()]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files for uploads (logo, product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage configurations for local media and WhiteNoise static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production Security Configurations
if not DEBUG:
    # Tell Django it's running behind a reverse proxy that terminates SSL (like Railway's load balancer)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Redirect HTTP traffic to HTTPS (disabled by default to prevent internal health check redirection failures)
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ['true', '1']
    # Ensure session and CSRF cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() in ['true', '1']
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() in ['true', '1']
    # Browser security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # HSTS settings (1 year duration)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Clickjacking protection
    X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# Logging Configuration
# Streams all WARNING+ level logs to stdout, which Railway captures centrally.
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
