web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python seed_db.py && gunicorn handmade_backend.wsgi --bind 0.0.0.0:${PORT:-8080} --workers 2 --timeout 120 --log-file -
release: python manage.py migrate --noinput

