# Generated by Django 6.0.6 on 2026-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aura Crafts', max_length=100)),
                ('site_name_ur', models.CharField(default='اورا کرافٹس', max_length=100)),
                ('site_title', models.CharField(default='Aura Crafts - Premium Handmade Home Décor', max_length=255)),
                ('site_title_ur', models.CharField(default='اورا کرافٹس - پریمیم ہینڈ میڈ ہوم ڈیکور', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_title', models.CharField(default='Handcrafted Treasures for Your Sanctuary', max_length=255)),
                ('hero_title_ur', models.CharField(default='ہاتھ سے بنے شاہکار آپ کے خوبصورت گھر کے لیے', max_length=255)),
                ('hero_sub', models.TextField(default='Immerse your space in the stories of global master craftsmen. Curated, sustainable, and heirloom-quality home decor.')),
                ('hero_sub_ur', models.TextField(default='اپنے گھر کو دنیا بھر کے ماہر دستکاروں کی کہانیوں سے سجائیں۔ منتخب، پائیدار اور شاندار ہوم ڈیکور۔')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
